name: Java Style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - name: Check code meets quality standards
      id: code-inspector
      uses: codeinspectorio/github-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
        code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
        min_quality_grade: 'NEUTRAL'
        min_quality_score: '50'
        max_defects_rate: '0.0001'
        max_complex_functions_rate: '0.5'
        max_long_functions_rate: '0.5'
        project_name: ''
        max_timeout_sec: '600'
  check-java-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 12

    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.2.0
